  spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/tch
      username: tch
      password: knofensa
    jpa:
      hibernate:
        ddl-auto: validate # validate update create create-drop
    h2:
      console:
        enabled: true
