  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/tch
      username: springuser
      password: springpassword
    jpa:
      hibernate:
        ddl-auto: validate # validate update create create-drop
