  spring:
    datasource:
      url: jdbc:h2:mem:tch
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
    jpa:
      hibernate:
        ddl-auto: create # validate update create create-drop
    h2:
      console:
        enabled: true
