  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/tch
      username: tch
      password: knofensa
    jpa:
      hibernate:
        ddl-auto: validate # validate update create create-drop